website/__init__.py
# coding: utf-8
"""redcatstudio.com.ua website
@author: Andrew Popovych <piratus@gmail.com>
"""
import os
from flask import Flask, render_template
from website.database import db, Photo
from website.assets import assets

# Config
app = Flask(__name__)
app.config.from_pyfile('settings.py')

# Init database
db.init_app(app)

#Init assets
assets.init_app(app)


# Views
@app.route('/')
def index():
    """Main view where the portfolio will be"""
    return render_template('index.html',
                           selected='index',
                           photos=Photo.query.limit(32).all())


from .views import admin, gallery, pages, panoramas
app.register_blueprint(admin)
app.register_blueprint(gallery)
app.register_blueprint(pages)
app.register_blueprint(panoramas)

from .views.pages import MenuExtension
app.jinja_env.add_extension(MenuExtension)


def static(pagename):
    """Displays template and adds it's name to params for navigation"""
    def view():
        return render_template('{0}.html'.format(pagename), selected=pagename)
    return view

@app.before_first_request
def ensure_upload_paths():
    for path in [app.config['PHOTO_PATH'], app.config['PANORAMA_PATH']]:
        if not os.path.exists(path):
            os.makedirs(path)

website/views/__init__.py
from .admin import mod as admin
from .gallery import mod as gallery
from .pages import mod as pages
from .panoramas import mod as panoramas

website/views/admin/__init__.py
# coding: utf-8
""" Admin views for redcatstudio """

from flask import Blueprint, render_template

from .auth import login_required, login, logout
from .gallery import AlbumAPI, update_album_order, PhotoAPI, update_photo_order
from .pages import PagesAPI, update_page_order
from .panoramas import PanoramasAPI

mod = Blueprint('admin', __name__, url_prefix='/admin', static_folder='static')


@login_required
def index():
    return render_template('admin/index.html')

mod.add_url_rule('/', view_func=index, methods=['GET'])
mod.add_url_rule('/login/', view_func=login, methods=['GET', 'POST'])
mod.add_url_rule('/logout/', view_func=logout, methods=['GET'])


albums_view = AlbumAPI.as_view('album_api')
mod.add_url_rule('/api/albums/', defaults={'album_id': None},
                 view_func=albums_view, methods=['GET'])
mod.add_url_rule('/api/albums/', view_func=albums_view, methods=['POST'])
mod.add_url_rule('/api/albums/<int:album_id>/', view_func=albums_view,
                 methods=['GET', 'PUT', 'DELETE'])
mod.add_url_rule('/api/albums/update_order/', view_func=update_album_order,
                 methods=['POST'])


photos_view = PhotoAPI.as_view('photo_api')
mod.add_url_rule('/api/photos/', view_func=photos_view, methods=['POST'])
mod.add_url_rule('/api/photos/<int:photo_id>/', view_func=photos_view,
                 methods=['GET', 'DELETE'])
mod.add_url_rule('/api/albums/<int:album_id>/update_order/',
                 view_func=update_photo_order, methods=['POST'])


panoramas_view = PanoramasAPI.as_view('panoramas_api')
mod.add_url_rule('/api/panoramas/', view_func=panoramas_view,
                 methods=['GET'], defaults={'pano_id': None})
mod.add_url_rule('/api/panoramas/', view_func=panoramas_view, methods=['POST'])
mod.add_url_rule('/api/panoramas/<int:pano_id>/', view_func=panoramas_view,
                 methods=['GET', 'PUT', 'DELETE'])


pages_view = PagesAPI.as_view('pages_api')
mod.add_url_rule('/api/pages/', view_func=pages_view,
                 methods=['GET'], defaults={'page_id': None})
mod.add_url_rule('/api/pages/', view_func=pages_view, methods=['POST'])
mod.add_url_rule('/api/pages/<int:page_id>/', view_func=pages_view,
                 methods=['GET', 'PUT', 'DELETE'])
mod.add_url_rule('/api/pages/update_order/', view_func=update_page_order,
                 methods=['POST'])

website/views/admin/auth.py
# coding: utf-8
from functools import wraps
from flask import session, request, redirect, url_for, render_template, flash
from website.settings import ADMINS


def login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if not session.get('logged_in', False):
            if request.is_xhr:
                return 'Not authorised', 401
            return redirect(url_for('admin.login'))
        return func(*args, **kwargs)

    return wrapper


def login():
    """A mock for login"""
    users = {name: password for name, password in ADMINS}
    if request.method == 'POST':
        name = request.form.get('username', None)
        password = request.form.get('password', None)
        if not (name and name in users and users[name] == password):
            flash(u'Неправильное имя или пароль')
            return redirect(url_for('admin.login'))
        session['logged_in'] = True

    if session.get('logged_in', False):
        return redirect(url_for('admin.index'))

    return render_template('admin/login.html')


def logout():
    """A mock logout"""
    session.pop('logged_in', None)
    return redirect(url_for('admin.login'))

website/views/gallery.py
# coding: utf-8
import os

from flask import (Blueprint, render_template, request, abort,
                   send_from_directory)
from website.database import Album
from website.settings import PHOTO_PATH
from website.thumbnailer import create_thumbnail
from website.utils import extend_filename


mod = Blueprint('gallery', __name__,
                url_prefix='/albums', static_folder='static')


@mod.route('/')
def list_albums():
    albums = Album.query.order_by(Album.order).all()
    return render_template('albums_list.html', albums=albums,
                           selected='gallery')


@mod.route('/<slug>/')
def album(slug):
    #FIXME: optimize
    album_obj = Album.query.filter(Album.slug == slug).first()
    albums = Album.query.order_by(Album.order).all()
    if album_obj is None:
        abort(404)
    return render_template('album_detail.html',
                           album=album_obj, albums=albums, selected='gallery')


@mod.route('/photos/<filename>')
def show_photo(filename):
    size = request.args.get('size', False)
    crop = request.args.get('crop', True)
    if size:
        new_filename = extend_filename(filename, size)
        if not os.path.exists(os.path.join(PHOTO_PATH, new_filename)):
            create_thumbnail(os.path.join(PHOTO_PATH, filename), size, crop)
        filename = new_filename

    return send_from_directory(PHOTO_PATH, filename)

website/views/pages.py
# coding: utf-8
from flask import (Blueprint, render_template, abort, request, redirect, flash,
                   url_for)
from jinja2 import nodes
from jinja2.ext import Extension
from sqlalchemy.orm import aliased
from website.database import db, Message, Page, PAGES_TEMPLATES


mod = Blueprint('pages', __name__, url_prefix='')


@mod.route('/<path:slug>/')
def view_page(slug):
    page = Page.query.filter(Page.slug == slug).first()
    if not page:
        abort(404)
    template = PAGES_TEMPLATES.get(page.template, 'pages/basic.html')
    return render_template(template, page=page)


@mod.route('/<slug>/', methods=['POST'])
def post_message(slug):
    data = request.form
    fields = ['name', 'email', 'message']
    if any(len(data.get(field, '')) == 0 for field in fields):
        flash(u'Нужно заполнить все поля формы.', 'error')
    else:
        db.session.add(Message(data['name'], data['email'], data['message']))
        db.session.commit()
        flash(u'Ваше сообщение успешно отправлено.')
    return redirect(request.headers.get('Referer', '/%s/' % slug))


class MenuExtension(Extension):
    tags = {'menu', 'submenu'}
    endtags = {'name:endmenu', 'name:endsubmenu'}

    def parse(self, parser):
        method_name = '_create_{0}'.format(parser.stream.current.value)
        lineno = parser.stream.next().lineno
        body = parser.parse_statements(self.endtags, drop_needle=True)
        params = [
            nodes.Name('title', 'store'),
            nodes.Name('url', 'store'),
            nodes.Name('selected', 'store')
        ]
        method = self.call_method(method_name, args=[])
        return nodes.CallBlock(method, params, [], body).set_lineno(lineno)

    def _create_menu(self, caller):
        gallery_path = url_for('gallery.list_albums')
        panoramas_path = url_for('panoramas.list_panoramas')
        result = (
            caller(u'Галлерея', gallery_path, gallery_path == request.path) +
            caller(u'Панорамы', panoramas_path, panoramas_path == request.path)
        )
        for page in Page.query.order_by(Page.order)\
                .filter(Page.published == True)\
                .filter(Page.parent == None):
            gallery_path = url_for('pages.view_page', slug=page.slug)
            result += caller(page.menu_title, gallery_path, request.path == gallery_path)
        return result

    def _create_submenu(self, caller):
        slug = str(request.path[1:-1].split('/')[0])
        result = ''
        parent = aliased(Page)
        query = Page.query.join(parent, "parent").filter(parent.slug == slug)
        for page in query:
            path = url_for('pages.view_page', slug=page.slug)
            result += caller(page.menu_title, path, request.path == path)
        return result

website/views/panoramas.py
# coding: utf-8
from flask import Blueprint, render_template, request
from flask.helpers import url_for
from website.database import Panorama


mod = Blueprint('panoramas', __name__,
                url_prefix='/panoramas', static_folder='static')


@mod.route('/')
def list_panoramas():
    panoramas = Panorama.query\
        .order_by(Panorama.date_added)\
        .filter_by(published=True)

    return render_template('pano_list.html', panoramas=panoramas,
                           selected='panoramas')


@mod.route('/<int:pano_id>')
def view_panorama(pano_id):
    panorama = Panorama.query\
        .filter_by(published=True, id=pano_id)\
        .first_or_404()

    quality = request.args.get('quality')
    if not quality in {'mq', 'hq'}:
        quality = 'mq'
    filename = url_for('static', filename=panorama.file_for(quality))
    return render_template('pano_detail.html', panorama=panorama,
                           filename=filename, selected='panoramas')

website/templates/album_detail.html
{% extends "albums_list.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='js/libs/themes/folio/galleria.folio.css') }}">

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    {% assets 'galleria_js' %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}

    <script type="text/javascript">
        $(function() { $('#album_photos').galleria({width: 1000, height: 450}); });
    </script>
{% endblock %}

{% block content %}
<div id="album_photos">
{% for photo in album.photos %}
    <a class="thumbnail_link" href="{{ photo.url }}">
        <img class="photo_thumbnail" src="{{ photo.url }}?size=210">
    </a>
{% endfor %}
</div>
{% endblock %}

website/templates/albums_list.html
{% extends "base.html" %}

{% block submenu %}
    <ul id="submenu">
    {% for album in albums %}
        <li class="submenuitem"><a href="{{ url_for('gallery.album', slug=album.slug) }}">{{ album.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

{% block content %}
<ul class='albums unstyled'>
    {% for album in albums %}
        <li>
            <a href="{{ url_for('gallery.album', slug=album.slug) }}">
                <span>{{ album.name }}</span>
                <img src="{{ album.cover }}">
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

website/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>{% block title %}Фотостудия Red Cat{% endblock %}</title>
    {% block metas -%}
    <meta name="description" content="фотостудия в киеве аренда фотостудии в киеве фотограф в киеве фотосессия протфолио репортажная съемка свадебное фото свадебный фотограф">
    <meta name="keywords" content="фотостудия киев, аренда фотостудии, фотограф киев, фотосессия, протфолио, Семейная фотосессия, репортажная съемка, свадебное фото, свадебный фотограф">
    {%- endblock %}
    {% assets 'style_css' -%}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {%- endassets %}
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block head %}{% endblock %}
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32608507-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <a href="{{ url_for('index') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}">
        </a>
        <div id="menu">
            <ul id="mainmenu">
                {% menu %}<li class="mainmenuitem {% if selected %}selected{% endif %}"><a href="{{ url }}">{{ title }}</a> </li>{% endmenu %}
            </ul>
            {% block submenu %}
                <ul id="submenu">
                    {% submenu %}<li class="submenuitem {% if selected %}selected{% endif %}"><a href="{{ url }}">{{ title }}</a> </li>{% endsubmenu %}
                </ul>
            {% endblock %}
        </div>
        <div id="header-contacts">
            <p>095-737-02-13</p>
            <p>063-291-14-24</p>
        </div>
    </div>
    {% block content %}{% endblock %}
</div>
</body>
</html>

website/templates/contacts.html
{% extends "base.html" %}

{% block content %}
<div class="container">

<div class="row">
    <div class="span6">
        <dl class="big">
            <dt>Наш адрес:</dt>
                <dd>Киев, ул. Межевая, 15</dd>
            <dt>Наши телефоны:</dt>
            <dd>097-505-55-56 Евгений Жданов</dd>
            <dd>063-266-96-67</dd>
            <dd>063-291-14-24 Екатерина Царькова</dd>
            <dt>Наш email: </dt>
            <dd><a href="mailto:mail@redcatstudio.org">mail@redcatstudio.org</a></dd>
        </dl>
        <p><strong>Или ещё вот форма:</strong></p>
        <form class="form-stacked">
        <fieldset>
            <div class="clearfix">
                <label for="name">Ваше имя</label>
                <input class="name span5" name="name" type="text">
            </div>
            <div class="clearfix">
                <label for="email">e-mail</label>
                <input class="email span5" name="email" type="text">
            </div>
            <div class="clearfix">
                <label for="message">Сообщение</label>
                <textarea class="span5" name="message" id="message"></textarea>
            </div>
        </fieldset>
        <div class="actions">
            <input type="submit" value="отправить" class="btn">
        </div>
        </form>
    </div>
    <div class="span10">
            <div class="map">
            <iframe width="570" height="460" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.ru/maps?f=q&amp;source=s_q&amp;hl=ru&amp;geocode=&amp;q=15+%D0%9C%D0%B5%D0%B6%D0%B5%D0%B2%D0%B0%D1%8F+%D1%83%D0%BB%D0%B8%D1%86%D0%B0,+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&amp;aq=t&amp;sll=55.354135,40.297852&amp;sspn=35.135936,63.896484&amp;vpsrc=6&amp;ie=UTF8&amp;hq=&amp;hnear=%D0%9C%D0%B5%D0%B6%D0%B5%D0%B2%D0%B0%D1%8F+%D1%83%D0%BB.,+15,+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&amp;ll=50.515701,30.436993&amp;spn=0.009456,0.0156&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="http://maps.google.ru/maps?f=q&amp;source=embed&amp;hl=ru&amp;geocode=&amp;q=15+%D0%9C%D0%B5%D0%B6%D0%B5%D0%B2%D0%B0%D1%8F+%D1%83%D0%BB%D0%B8%D1%86%D0%B0,+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&amp;aq=t&amp;sll=55.354135,40.297852&amp;sspn=35.135936,63.896484&amp;vpsrc=6&amp;ie=UTF8&amp;hq=&amp;hnear=%D0%9C%D0%B5%D0%B6%D0%B5%D0%B2%D0%B0%D1%8F+%D1%83%D0%BB.,+15,+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%9A%D0%B8%D0%B5%D0%B2,+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&amp;ll=50.511701,30.435991&amp;spn=0.009456,0.0156&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Просмотреть увеличенную карту</a></small>
        </div>
    </div>
</div>

</div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block title %}Фотограф Киев. Услуги фотографа в Киеве, профессиональная фотосъемка{% endblock %}
{% block metas %}<meta name="description" content="Услуги профессионального фотографа в Киеве. Закажите качественные снимки, фотосъемку событий, торжеств или просто фотосессию у нас в студии на Оболони, всегда Вам рады">{% endblock %}


{% block content %}
    <ul id="index-photos" class="unstyled">
    {% for photo in photos %}
        <li><a class="thumbnail_link" href="{{ url_for('gallery.album', slug=photo.album.slug) }}#/{{ photo.order - 1 }}">
            <img class="photo_thumbnail" src="{{ photo.url }}?size=100" alt="">
        </a></li>
    {% endfor %}
    </ul>
{% endblock %}

website/templates/pano_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="hero-unit center">
    <h3>{{ panorama.name }}</h3>
    <div id="panorama-container">
      <p><a href="http://www.adobe.com/go/getflashplayer">
        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p>
    </div>
    <script src="{{ url_for('static', filename='js/libs/swfobject.js') }}"></script>
    <script type="text/javascript">
      var flashvars = {},
        filename = '{{ filename }}',
        params = {quality: "high", bgcolor: "#ffffff",
          allowscriptaccess: "sameDomain", allowfullscreen: "true",
          base: "."},
        attributes = {id: "pano", name: "pano", align: "middle"};

      swfobject.embedSWF(filename, 'panorama-container','849', '608',
        '9.0.0', 'expressInstall.swf', flashvars, params, attributes)
    </script>
  </div>
{% endblock %}

website/templates/pano_list.html
{% extends "base.html" %}

{% block content %}
<ul class="panoramas unstyled">
  {% for panorama in panoramas %}
    <li>
      <p class="title">{{ panorama.name }}</p>
      <img src="{{ panorama.preview_image }}">
      <p class="links">Смотреть:
        {% if panorama.mq_file_size -%}
          <a href="{{ panorama.url_for('mq') }}">4000px</a>
{#          <span>({{ panorama.mq_file_size|filesizeformat }})</span>#}
        {%- endif %}
        {% if panorama.hq_file_size -%}
          <a href="{{ panorama.url_for('hq') }}">8000px</a>
{#          <span>({{ panorama.hq_file_size|filesizeformat }})</span>#}
        {%- endif %}
      </p>
    </li>
  {% endfor %}
</ul>
{% endblock %}

website/templates/rent.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div class="row">
			<div class="span10">
			<h1 class="center">Аренда оборудования</h1>
				<table>
					<tbody>
					<tr>
						<th>Моноблоки</th>
						<td>
							<ul>
								<li>Hyundae Photonics Combi 1000</li>
								<li>Hyundae Photonics Combi 600</li>
								<li>Hyundae Photonics Combi 400 (2 шт)</li>
								<li>Arsenal VC-300</li>
							</ul>
						</td>
					</tr>
					<tr>
						<th>Рефлекторы</th>
						<td>
							<ul>
								<li>Рефлектор Arsenal ARS стандартный&nbsp;(2 шт)</li>
								<li>Набор Arsenal BD-200 (шторки, соты, 4 цветных фильтра)</li>
								<li>Портретная тарелка Beauty Dish 41 см.</li>
								<li>Портретная тарелка Arsenal 56 см.</li>
								<li>Рефлектор Hyundae Snoot Honey 70 мм. (конус с сотами)</li>
							</ul>
						</td>
					</tr>
					<tr>
						<th>Софтбоксы</th>
						<td>
							<ul>
								<li>Октогон ACE Hyundae Photonics PSOR 200 см</li>
								<li>Софтбокс 60х90 см. (2шт)</li>
								<li>Софтбокс 80х120 см.</li>
								<li>Софтбокс 35х140 см.</li>
								<li>Студийный зонт на отражение (2 шт.)</li>
							</ul>
						</td>
					</tr>
					<tr>
						<th>Фоны бумажные 2.7х11м</th>
						<td>
							<ul>
								<li>Нейтрально серый</li>
								<li>Черный</li>
								<li>Белый</li>
							</ul>
						</td>
					</tr>
					<tr>
						<th>Фоны тканевые</th>
						<td>
							<ul><li>Черный бархатный 2штх1.35х5м</li></ul>
						</td>
					</tr>
					<tr>
						<th>Синхронизация</th>
						<td>
							<ul>
								<li>Радиосинхронизатор</li>
								<li>Синхрошнуры - 5м (4шт)</li>
							</ul>
						</td>
					</tr>
					<tr>
						<th>Прочее</th>
						<td>
							<ul>
								<li>Студийная стойка Arsenal - 3 шт.</li>
								<li>Студийная стойка Weifeng - 2 шт.</li>
								<li>Журавль - 1 шт.</li>
								<li>Держатель для отражателя - 1 шт.</li>
								<li>Штатив Slic - 1 шт.</li>
								<li>Отражатель - 2 шт.</li>
							</ul>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="span6 highlight">
			<h1 class="center">Аренда Фотостудии</h1>
			<table cellspacing="0" cellpadding="0">
				<tbody>
				<tr>
					<th>Дни</th>
					<th>Часы</th>
					<th>Стоимость</th>
				</tr>
				<tr>
					<td>Будние</td>
					<td>09:00 &mdash; 20:00</td>
					<td>100 грн/час</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>20:00 &mdash; 24:00</td>
					<td>120 грн/час</td>
				</tr>
				<tr>
					<td>Выходные</td>
					<td>09:00 &mdash; 18:00</td>
					<td>100 грн/час</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>18:00 &mdash; 24:00</td>
					<td>120 грн/час</td>
				</tr>
				<tr>
					<td>Фотоночь</td>
					<td>20:00 &mdash; 08:00</td>
					<td>700 грн</td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="span6 offset4">
			{#<img src="http://cs11265.vkontakte.ru/u5958409/126143565/x_95b653ac.jpg" alt="Съемочный павильон ">#}
		</div>
	</div>
</div>
{% endblock %}

website/templates/services.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="span8">
			<h3>Студийная фотосессия</h3>
			<table>
				<tbody>
					<tr>
						<th>&nbsp;</th>
						<th>Цена в грн</th>
						<th></th>
					</tr>
					<tr>
						<td><strong>Мини портфолио.</strong> Часовая съемка одного-двух образов, до 50 фото на диске, 5 отретушированных и напечатанных фотографий.</td>
						<td>499</td>
					</tr>
					<tr>
						<td><strong>Портфолио. </strong>Двухчасовая съемка до трех образов, до 100&nbsp; фото на диске, 10 отретушированных и напечатанных фотографий.</td>
						<td>999</td>
					</tr>
					<tr>
						<td><strong>Расширенное портфолио. </strong>Трехчасовая съемка трех-четырех образов, до 200 фото на диске, 25 отретушированных и напечатанных фотографий.</td>
						<td>1599</td>
					</tr>
					<tr>
						<td><strong>Детская </strong>полуторачасовая съемка, до 75 фото на фото на диске, 10 отретушированных и напечатанных фотографий.</td>
						<td>499</td>
					</tr>
					<tr>
						<td><strong>Семейная </strong>часовая съемка до 50&nbsp; фото на диске, 10 отретушированных и напечатанных фотографий.</td>
						<td>999</td>
					</tr>
					<tr>
						<td><strong>Рекламная фотосъемка </strong></td>
						<td>договорная</td>
					</tr>
					<tr>
						<td><strong>Предметная съемка</strong> без обработки</td>
						<td>от 30 /фото</td>
					</tr>
					<tr>
						<td><strong>Предметная съемка</strong> с обработкой</td>
						<td>от 50 /фото</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="span8">
			<h3>Выездная фотосъёмка</h3>
			<table>
				<tbody>
					<tr><th></th><th>Цена&nbsp;в&nbsp;грн.</th></tr>
					<tr>
						<td><strong>Love story</strong> на 1 час. до 50 фото на диске, 5 отретушированных и напечатанных фотографий.</td>
						<td>299</td>
					</tr>
					<tr>
						<td><strong>Репортажная съемка</strong></td>
						<td>от 100 /час</td>
					</tr>
				</tbody>
			</table>
			<h3>Свадебная съёмка</h3>
			<table>
				<tbody>
					<tr><th></th><th>Цена&nbsp;в&nbsp;грн.</th></tr>
					<tr>
						<td>Постановочная и репортажная съемка до первого танца, до 500 обработанных фото на диске, 50 отретушированных с художественной обработкой</td>
						<td>от 3500</td>
					</tr>
					<tr>
						<td>Сюжетная постановочная съемка свадьбы с написанием сценария, до 500 обработанных фото на диске, 50 отретушированных с художественной обработкой</td>
						<td>от 4500</td>
					</tr>
					<tr>
						<td>Съемка после первого танца</td>
						<td>от 1000</td>
					</tr>
				</tbody>
			</table>
			<h3>Изготовление фотокниг</h3>
			<table>
				<tbody>
					<tr>
						<td>Формат фотокниги 30х30 см.
							<ul>
								<li>Матовая бумага</li>
								<li>Шелковая бумага</li>
								<li>Обложка с фотографий</li>
								<li>Обложка с кожзаменителя</li>
					 		</ul>
						</td>
						<td>цена&nbsp;за&nbsp;разворот
							<ul>
								<li>72</li>
								<li>84</li>
								<li>480</li>
								<li>768</li>
							</ul>
						</td>
					<tr>
						<td>Выездная фотосессия с использованием студийного оборудования</td>
						<td>+30% к стоимости</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}